language: clojure
lein: lein
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
  # - oraclejdk7
  # - openjdk7
env:
  matrix:
    - VERSION='1.5'
    - VERSION='1.6'
    - VERSION='1.7'
    - VERSION='1.8'
    - VERSION='1.9'
script: lein with-profile dev,$VERSION midje
after_success:
  - CLOVERAGE_VERSION=1.0.9 lein cloverage --codecov
  - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
