language: clojure
lein: 2.8.1
cache:
  directories:
    - $HOME/.m2
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  - openjdk9
  - openjdk10
  - openjdk11
before_script:
  - lein version
env:
  matrix:
    - VERSION='1.7'
    - VERSION='1.8'
    - VERSION='1.9'
    - VERSION='1.10'
before_install: if [ -f "${JAVA_HOME}/lib/security/cacerts" -a -w  "${JAVA_HOME}/lib/security/cacerts" ]; then rm "${JAVA_HOME}/lib/security/cacerts" && ln -s /etc/ssl/certs/java/cacerts "${JAVA_HOME}/lib/security/cacerts"; fi
script: lein with-profile dev,$VERSION midje
jobs:
  include:
    - stage: coverage
      jdk: openjdk8
      script:
        - lein cloverage --codecov
        - bash <(curl -s https://codecov.io/bash) -f target/coverage/codecov.json
